security:
  oauth2:
    client:
      client-id: my-user
      client-secret: secret
      access-token-uri: http://localhost:8080/oauth/token
server:
  port: 8080

  currency:
    uah:
      usd: 0.037
      eur: 0.032
    usd:
      uah: 27.28
      eur: 0.88
    eur:
      uah: 30.83
      usd: 1.13